services:
  - type: web
    name: backend-api
    env: python
    plan: free
    rootDir: proyectottb
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
